[package]
name = "provenance-storage"
version = "0.1.0"
edition = "2024"

[lib]
name = "provenance_storage"
path = "src/lib.rs"

[dependencies]
fs2 = { workspace = true }
postcard = { workspace = true }
provenance-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
